# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=50)),
                ('register_time', models.DateTimeField()),
                ('gender', models.IntegerField(default=-1)),
                ('user_photo', models.CharField(max_length=200)),
                ('lover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.User')),
            ],
        ),
    ]
